"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import TQHeader from "../components/TQHeader"
// import Header from "@/components/Header";

const LOCALE = 'en';

import {
  AppLayout,
  BreadcrumbGroup,
  Button,
  Container,
  ContentLayout,
  Flashbar,
  Header,
  HelpPanel,
  Link,
  SideNavigation,
  SpaceBetween,
  SplitPanel,
} from '@cloudscape-design/components';

import { I18nProvider } from '@cloudscape-design/components/i18n';
import messages from '@cloudscape-design/components/i18n/messages/all.en';



import "@cloudscape-design/global-styles/index.css"
import { FaHamburger } from "react-icons/fa";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "The Quran Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const currentRoute = usePathname()
  return (
    <html lang="en">
      <body className="" >
        <TQHeader /> 
      <I18nProvider  locale={LOCALE} messages={[messages]}>
      <AppLayout      
        breadcrumbs={
          <BreadcrumbGroup 
          items={[
            { text: 'Home', href: '#' },
            { text: currentRoute, href: '#' },
          ]}
          />
        }        
        // navigationOpen={}
        navigation={
        <Sidebar/>
        }
        // toolsOpen={true}
        // tools={<HelpPanel header={<h2>Overview</h2>}>Help content</HelpPanel>}
        content={
          <ContentLayout
            header={
              <Header variant="h1" info={<Link variant="info">Info</Link>}>
                Page header
              </Header>
            }
          >
          {/* main content  */}
        
          {children}
          </ContentLayout>
        }
      />
    </I18nProvider>
        </body>
    </html>
  );
}
